### ISSUE TITLE
Limit for connections not working ?

### ISSUE THREAD

**Issue by ghost** [OpendataCH/Transport#128] opened 2016-04-27 12:24 UTC
I've been trying to get only one connection from a city (e.g. Aarau ) to another (e.g. Aarberg ) and even after passing the limit parameter to the request URL there are more than 10 connections returned . Am I doing something wrong ? This is the request URL I tried to use http://transport.opendata.ch/v1/connections?from=Aarau&to=Aarberg&limit=1 . Am I using the parameter incorrectly ? The documentation for the parameter is pretty vague as it doesn't say how to request less connections all it says is this.
![capture](https://cloud.githubusercontent.com/assets/18700113/14851952/0459f48c-0c8c-11e6-81d1-1918b385a0be.PNG)

**Comment by fabian** [comment] 2016-04-27 12:47
Two connections are returned because they depart at the same time (14:46).

This is as documented.

Unfortunately at the moment there's no way to avoid this in the Transport API, you will have to further filter the connections on the client.

Closing as duplicate of https://github.com/OpendataCH/Transport/issues/51

**Closed by fabian** 2016-04-27 12:47 UTC
Labels: question
